import { test, expect } from '@playwright/test';
import { createClient } from '@supabase/supabase-js';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
const local = JSON.parse(execFileSync('npx', ['supabase', 'status', '-o', 'json'], { encoding: 'utf8' }));
if (!['localhost', '127.0.0.1'].includes(new URL(local.API_URL).hostname)) throw new Error('Local stack required');
const db = createClient(local.API_URL, local.SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const org = randomUUID(), category = randomUUID(), tree = randomUUID(), node = randomUUID(), dx = randomUUID();
const email = `${org}@resolve.test`, password = `Test-${randomUUID()}!`;
let user: string;
const ok = (r: any) => { expect(r.error).toBeNull(); return r.data; };
test.beforeAll(async () => {
  ok(await db.from('organizations').insert({ id: org, name: 'Browser test', slug: org }));
  user = ok(await db.auth.admin.createUser({ email, password, email_confirm: true })).user.id;
  ok(await db.from('users').insert({ id: user, org_id: org, role: 'admin', email, full_name: 'Live admin' }));
  ok(await db.from('diagnostic_categories').insert({ id: category, org_id: org, slug: 'connection', label: 'Connection', short_label: 'Connection' }));
  ok(await db.from('diagnoses').insert({ id: dx, org_id: org, key: 'connection', title: 'Check your connection.', short_label: 'Connection', node_label: 'Connection' }));
  ok(await db.from('troubleshooting_steps').insert({ diagnosis_id: dx, position: 1, title: 'Reconnect', detail: 'Reconnect the cable.' }));
  ok(await db.from('diagnostic_trees').insert({ id: tree, category_id: category, version: 1, root_label: 'Connection' }));
  ok(await db.from('diagnostic_nodes').insert({ id: node, tree_id: tree, key: 'root', question: 'Is the cable connected?', fact_label: 'Cable', short_label: 'Cable' }));
  ok(await db.from('diagnostic_options').insert({ node_id: node, label: 'Yes', fact_value: 'Connected', diagnosis_id: dx }));
  ok(await db.from('diagnostic_trees').update({ root_node_id: node, status: 'published' }).eq('id', tree));
});
test.afterAll(async () => {
  ok(await db.from('tickets').delete().eq('org_id', org));
  ok(await db.from('diagnostic_sessions').delete().eq('org_id', org));
  ok(await db.from('diagnostic_trees').update({ root_node_id: null }).eq('category_id', category));
  ok(await db.from('diagnostic_trees').delete().eq('category_id', category));
  if (user) ok(await db.auth.admin.deleteUser(user));
  ok(await db.from('organizations').delete().eq('id', org));
});
test.beforeEach(async ({ page }) => {
  page.on('pageerror', error => { throw error; });
  await page.goto('./');
  await page.getByLabel('Work email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: "What's going wrong?" })).toBeVisible();
});
test('refresh restores database state during questions, fixes and before escalation', async ({ page }) => {
  await page.getByRole('button', { name: 'Connection', exact: true }).click();
  await page.getByRole('button', { name: 'Start', exact: true }).dblclick();
  await expect(page.getByText('Is the cable connected?')).toBeVisible();
  await page.reload();
  await expect(page.getByText('Is the cable connected?')).toBeVisible();
  await page.goto('about:blank');
  await page.goBack();
  await expect(page.getByText('Is the cable connected?')).toBeVisible();
  await page.route('**/rest/v1/rpc/answer_question', async route => {
    await route.fetch(); // The write committed, but the caller loses its response.
    await route.fulfill({ status: 503, contentType: 'application/json', body: '{}' });
  }, { times: 1 });
  await page.getByRole('button', { name: 'Yes', exact: true }).click();
  await page.getByRole('button', { name: 'Reload saved progress' }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Try this' })).toBeVisible();
  await page.getByRole('button', { name: 'Try this' }).click();
  await page.getByRole('button', { name: 'Still not working' }).click();
  await expect(page.getByRole('button', { name: 'Send to IT', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Send to IT', exact: true })).toBeVisible();
  const sessionId = await page.evaluate(() => localStorage.getItem('resolve.activeSessionId'));
  await page.getByRole('button', { name: 'Send to IT', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'On its way.' })).toBeVisible();
  expect(ok(await db.from('session_answers').select('*').eq('session_id', sessionId)).length).toBe(1);
  await page.getByRole('button', { name: 'See it in the IT desk' }).click();
  await page.getByRole('button', { name: /^Open RSV/ }).click();
  await expect(page.getByRole('dialog').getByText('Connected', { exact: true })).toBeVisible();
  await page.route('**/rest/v1/rpc/add_ticket_note', route => route.fulfill({ status: 503, body: '{}' }), { times: 1 });
  await page.getByLabel('Add an internal note').fill('Keep this note if saving fails.');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();
  await expect(page.getByLabel('Add an internal note')).toHaveValue('Keep this note if saving fails.');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('.notes p')).toContainText('Keep this note if saving fails.');
});
test('stale session offers recovery and failed queue load offers retry', async ({ page }) => {
  await page.evaluate(() => localStorage.setItem('resolve.activeSessionId', '00000000-0000-0000-0000-000000000001'));
  await page.reload();
  await expect(page.getByText("We couldn't restore your support session.", { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Start a new request' }).click();
  let fail = true;
  await page.route('**/rest/v1/rpc/queue_stats', route => fail ? route.fulfill({ status: 503, body: '{}' }) : route.continue());
  await page.getByRole('button', { name: 'IT desk', exact: true }).click();
  await expect(page.getByText("We couldn't load the support queue. Try again.")).toBeVisible();
  await expect(page.getByText('Loading the queue…')).toHaveCount(0);
  fail = false;
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Refresh queue' })).toBeVisible();
});
test('expired authorization returns to sign-in without exposing backend details', async ({ page }) => {
  await page.route('**/rest/v1/rpc/start_session', route => route.fulfill({ status: 401, contentType: 'application/json', body: JSON.stringify({ code: 'PGRST301', message: 'Internal JWT parser detail' }) }));
  await page.getByRole('button', { name: 'Connection', exact: true }).click();
  await page.getByRole('button', { name: 'Start', exact: true }).click();
  await expect(page.getByLabel('Work email')).toBeVisible();
  await expect(page.getByText('Internal JWT parser detail')).toHaveCount(0);
});

test('draft preview creates no sessions and backend history is read-only', async ({ page }) => {
  const before = ok(await db.from('diagnostic_sessions').select('id').eq('org_id', org));
  let started = 0;
  page.on('request', r => { if (/rpc\/(start_session|escalate_session)/.test(r.url())) started++; });
  await page.getByRole('button', { name: 'Questions', exact: true }).click();
  await page.getByRole('button', { name: 'Preview saved questions' }).click();
  const preview = page.getByRole('region', { name: 'Draft preview' });
  await preview.getByRole('button', { name: 'Yes', exact: true }).click();
  await expect(preview.getByRole('heading', { name: 'Connection', exact: true })).toBeVisible();
  await preview.getByRole('button', { name: 'Exit preview' }).click();
  expect(started).toBe(0);
  expect(ok(await db.from('diagnostic_sessions').select('id').eq('org_id', org))).toEqual(before);
  await page.getByLabel('Version history').selectOption({ index: 1 });
  await expect(page.getByLabel('Answer text').first()).toBeDisabled();
});

test('live public reply moves waiting to needs review without exposing internal notes', async ({ page }) => {
  const requesterEmail = `${randomUUID()}@resolve.test`, requesterPassword = `Test-${randomUUID()}!`;
  const requesterId = ok(await db.auth.admin.createUser({ email: requesterEmail, password: requesterPassword, email_confirm: true })).user.id;
  const requester = createClient(local.API_URL, local.ANON_KEY, { auth: { persistSession: false } });
  try {
    // Prove Auth alone grants no arbitrary organization access, even with metadata.
    ok(await requester.auth.signInWithPassword({ email: requesterEmail, password: requesterPassword }));
    expect(ok(await requester.from('users').select('id'))).toEqual([]);
    await page.getByRole('button', { name: /^Sign out/ }).click();
    await page.getByLabel('Work email').fill(requesterEmail);
    await page.getByLabel('Password').fill(requesterPassword);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(page.getByText('Your account is awaiting access.', { exact: true })).toBeVisible();
    ok(await db.from('users').insert({ id: requesterId, org_id: org, role: 'end_user', email: requesterEmail, full_name: 'Live requester' }));
    await page.getByRole('button', { name: 'Check access' }).click();
    await expect(page.getByRole('heading', { name: "What's going wrong?" })).toBeVisible();
    let s = ok(await requester.rpc('start_session', { p_category_id: category, p_description: '', p_device: 'Laptop', p_operating_system: 'macOS' }));
    s = ok(await requester.rpc('answer_question', { p_session_id: s.id, p_option_id: s.node.options[0].id }));
    const ticket = ok(await requester.rpc('escalate_session', { p_session_id: s.id, p_note: '' }));
    await page.getByRole('button', { name: /^Sign out/ }).click();
    await page.getByLabel('Work email').fill(email); await page.getByLabel('Password').fill(password);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await page.getByRole('button', { name: 'IT desk', exact: true }).click();
    await page.getByRole('button', { name: `Open ${ticket.reference} from Live requester`, exact: true }).click();
    const dialog = page.getByRole('dialog');
    await expect(dialog.getByText('No additional description provided.')).toBeVisible();
    await dialog.getByRole('button', { name: 'Assign to me', exact: true }).click();
    await dialog.getByLabel('Attach image').setInputFiles('tests/fixtures/support.png');
    await expect(dialog.getByRole('button', { name: 'Remove support.png' })).toBeVisible();
    await dialog.getByLabel('Message', { exact: true }).fill('Staff screenshot');
    await dialog.getByRole('button', { name: 'Send message', exact: true }).click();
    await expect(dialog.getByLabel('Message', { exact: true })).toHaveValue('');
    await dialog.locator('.support-image').first().scrollIntoViewIfNeeded();
    await expect(dialog.getByRole('button', { name: 'View support.png' })).toBeVisible();
    await expect(dialog.locator('.ticket-workflow')).toContainText('assigned');
    await dialog.getByLabel('Add an internal note').fill('Private live inventory');
    await dialog.getByRole('button', { name: 'Add', exact: true }).click();
    await expect(dialog.getByLabel('Add an internal note')).toHaveValue('');
    await page.route('**/rest/v1/rpc/send_ticket_message', route => route.fulfill({ status: 503, body: '{}' }), { times: 1 });
    await dialog.getByRole('textbox', { name: 'Message', exact: true }).fill('Please check the cable.');
    await dialog.getByRole('button', { name: 'Send & wait for reply' }).click();
    await expect(dialog.getByRole('alert')).toBeVisible();
    await expect(dialog.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('Please check the cable.');
    await dialog.getByRole('button', { name: 'Send & wait for reply' }).click();
    await expect(dialog.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('');
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: /^Sign out/ }).click();
    await page.getByLabel('Work email').fill(requesterEmail); await page.getByLabel('Password').fill(requesterPassword);
    await page.getByRole('button', { name: 'Sign in', exact: true }).click();
    await page.getByRole('button', { name: 'My requests', exact: true }).click();
    await page.getByRole('button', { name: new RegExp(ticket.reference) }).click();
    await expect(page.getByText('Please check the cable.', { exact: true })).toBeVisible();
    await expect(page.getByText('Private live inventory')).toHaveCount(0);
    await page.locator('.support-image').first().scrollIntoViewIfNeeded();
    await expect(page.getByRole('button', { name: 'View support.png' })).toBeVisible();
    await page.getByRole('button', { name: 'View support.png' }).click();
    await expect(page.getByRole('dialog', { name: 'support.png' })).toBeVisible();
    await page.keyboard.press('Escape');
    const jpeg = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = 24; c.height = 24; c.getContext('2d')!.fillRect(0,0,24,24); return c.toDataURL('image/jpeg').split(',')[1]!; });
    await page.getByLabel('Attach image').setInputFiles({ name: 'device.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(jpeg, 'base64') });
    await expect(page.getByRole('button', { name: 'Remove device.png' })).toBeVisible();
    await page.getByRole('textbox', { name: 'Message', exact: true }).fill('It is connected.');
    await page.getByRole('button', { name: 'Send message', exact: true }).click();
    await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toHaveValue('');
    await expect(page.locator('.requests .label').filter({ hasText: 'IT is reviewing your reply' })).toBeVisible();
    const row = ok(await requester.from('tickets').select('status,assignee_id').eq('id', ticket.id))[0];
    expect(row.status).toBe('needs_review'); expect(row.assignee_id).toBe(user);
    await page.locator('.support-image').last().scrollIntoViewIfNeeded();
    await expect(page.getByRole('button', { name: 'View device.png' })).toBeVisible();
  } finally {
    await requester.auth.signOut();
    const attachments = ok(await db.from('ticket_attachments').select('object_path').eq('uploader_id', requesterId));
    const staffAttachments = ok(await db.from('ticket_attachments').select('object_path').eq('uploader_id', user));
    const paths = [...attachments, ...staffAttachments].map((a: any) => a.object_path);
    if (paths.length) ok(await db.storage.from('ticket-attachments').remove(paths));
    ok(await db.from('tickets').delete().eq('requester_id', requesterId));
    ok(await db.from('diagnostic_sessions').delete().eq('user_id', requesterId));
    ok(await db.auth.admin.deleteUser(requesterId));
  }
});

test('a delayed profile response cannot restore access after an auth-ended event', async ({ page }) => {
  let release!: () => void;
  let arrived!: () => void;
  const pending = new Promise<void>(resolve => { arrived = resolve; });
  const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/rest/v1/users?*', async route => {
    const response = await route.fetch(); arrived(); await gate;
    await route.fulfill({ response });
  }, { times: 1 });
  await page.reload({ waitUntil: 'domcontentloaded' });
  await pending;
  await page.evaluate(() => window.dispatchEvent(new Event('resolve:auth-expired')));
  release();
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'IT desk', exact: true })).toHaveCount(0);
});

test('initial image failure keeps the ticket, metadata failures keep edits, and retry attaches evidence', async ({ page }) => {
  await page.getByLabel('Describe the problem').fill('Initial issue');
  await page.getByLabel('Add a screenshot or photo (optional)').setInputFiles('tests/fixtures/support.png');
  await expect(page.getByRole('button', { name: 'Remove support.png' })).toBeVisible();
  await page.getByRole('button', { name: 'Connection', exact: true }).click();
  await page.getByRole('button', { name: 'Start', exact: true }).click();
  await page.getByRole('button', { name: 'Yes', exact: true }).click();
  await page.getByRole('button', { name: 'Skip ahead and send this to IT' }).click();
  await page.getByRole('button', { name: 'Edit issue details', exact: true }).click();
  await page.getByLabel('Problem description').fill('Corrected live report');
  await page.getByRole('combobox', { name: 'Device', exact: true }).selectOption('Phone');
  await page.getByRole('combobox', { name: 'System', exact: true }).selectOption('iOS');
  await page.route('**/rest/v1/rpc/update_session_details', route => route.fulfill({ status: 503, body: '{}' }), { times: 1 });
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await expect(page.getByLabel('Problem description')).toHaveValue('Corrected live report');
  await page.getByRole('button', { name: 'Save details' }).click();
  await expect(page.locator('.handoff')).toContainText('Corrected live report');
  await expect(page.locator('.handoff')).toContainText('Phone · iOS');
  await page.getByLabel('Additional note for IT (optional)').fill('Error appears when connecting.');
  await page.route('**/functions/v1/ticket-image*', route => route.fulfill({ status: 503, body: '{}' }), { times: 1 });
  await page.getByRole('button', { name: 'Send to IT', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Your request was sent');
  const ticket = ok(await db.from('tickets').select('*').eq('requester_id', user).eq('user_note', 'Error appears when connecting.').single());
  const metadata = ok(await db.from('diagnostic_sessions').select('description,device,operating_system,status').eq('id', ticket.session_id).single());
  expect(metadata).toMatchObject({ description: 'Corrected live report', device: 'Phone', operating_system: 'iOS', status: 'escalated' });
  expect(ok(await db.from('ticket_attachments').select('id').eq('ticket_id', ticket.id))).toHaveLength(0);
  await page.getByRole('button', { name: 'View my requests' }).click();
  await page.getByRole('button', { name: 'Retry attaching images' }).click();
  await expect(page.getByRole('button', { name: 'View support.png' })).toBeVisible();
  const attachments = ok(await db.from('ticket_attachments').select('object_path').eq('ticket_id', ticket.id));
  expect(attachments).toHaveLength(1);
  ok(await db.storage.from('ticket-attachments').remove(attachments.map((a: any) => a.object_path)));
  await page.reload();
  await page.getByRole('button', { name: 'My requests', exact: true }).click();
  await expect(page.getByRole('button', { name: new RegExp(ticket.reference) })).toBeVisible();
  await page.getByRole('button', { name: new RegExp(ticket.reference) }).click();
  await expect(page.locator('.request-detail .col-title')).toHaveText(ticket.reference);
  ok(await db.from('tickets').delete().eq('id', ticket.id));
  await page.getByRole('button', { name: 'Refresh requests' }).click();
  await expect(page.locator('.request-detail .col-title')).toHaveCount(0);
  await expect(page.locator('.request-detail')).toContainText('Select a request');
});
